POST http://localhost:3333/users
Content-Type:application/json

{
  "name": "rafinha",
  "email": "rafinha900@gmail.com",
  "password": "654a6s4a5s"
}

###

POST http://localhost:3333/sessions
Content-Type:application/json

{
  "email": "rafinha900@gmail.com",
  "password": "654a6s4a5s"
}

###

PATCH http://localhost:3333/token/refresh
Content-Type:application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NmU0ZTI3Ny0xNWJmLTQxODUtYjVhYi03MDQ4NmRiNGE4ZjMiLCJpYXQiOjE3MTY1NzU1MzEsImV4cCI6MTcxNzE4MDMzMX0.q-ut7D8qJTu9PTXqpvr17L9B3_sEsOyomkb3Has5TLs

{
  "email": "rafinha90@gmail.com",
  "password": "654a6s4a5s"
}

###

GET http://localhost:3333/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMmVlNjE5OC0xYjc2LTRhMzItYjI1OC0yMmY2YjgwNmQ1ODQiLCJpYXQiOjE3MTU4MTAyNjF9.gB2xkxStqCUjGs3jxf5rxHf-VITLOp2zR3hp97zH0D0
